spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      url: jdbc:h2:mem:usertdb
      username: sa
      password: sa
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: oghZzqIP/WUpAw3xSjq8bPsKqlQ0/ValEwTJNVx8GCE=
regex:
  password: ^(?=.*[A-Z])(?=.*[0-9])(?=.*[a-zA-Z]).{8,}$
  email: ^[A-Za-z0-9+_.-]+@(.+)$

